# Generated by Django 5.2.5 on 2025-11-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTestVocacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('nivel_educativo', models.CharField(max_length=255)),
                ('pregunta1', models.CharField(max_length=255)),
                ('pregunta2', models.CharField(max_length=255)),
                ('pregunta3', models.CharField(max_length=255)),
                ('pregunta4', models.CharField(max_length=255)),
                ('pregunta5', models.CharField(max_length=255)),
                ('area_predominante', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('carreras_recomendadas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
